name: Deploy to Staging

on:
  push:
    branches: [develop/*]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. リポジトリチェックアウト
      - uses: actions/checkout@v3

      # 2. Python セットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 依存関係インストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. PYTHONPATH 設定 & pytest 実行
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリチェックアウト
      - uses: actions/checkout@v3

      # 2. Python セットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Render CLI インストール
      - name: Install Render CLI
        run: |
          curl -L https://cli.render.com/install.sh | sh

      # 4. デプロイ
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
            render deploy --service-id ${{ secrets.RENDER_STAGING_SERVICE_ID }} --branch develop
